blank_issues_enabled: false
contact_links:
  - name: Postman Documentation Issues
    url: https://github.com/postmanlabs/postman-docs/issues/new
    about: Please file all documentation related issues here
  - name: Postman Learning Center
    url: https://learning.postman.com
    about: Learn how to use Postman in our Learning Center 
  - name: Postman Community Forum
    url: https://community.postman.com
    about: Get support and connect to the community on our forum
  - name: Postman Support Team
    url: https://support.postman.com/hc/en-us/requests/new/
    about: Open a new request with the Postman Support Team
